===============================================================
SUÍTE DE TESTES PARA A API IMPERIUM - USUÁRIOS
===============================================================
Variáveis Globais

@host = http://localhost:8080

################################################################

# Cria um novo usuário com todos os campos corretos
POST {{host}}/api/usuarios/registrar
Content-Type: application/json

{
    "nomeUsuario": "João Silva",
    "login": "joao.silva",
    "senha": "Senha123*",
    "setorUsuario": "Gerente"
}


################################################################

#2. CRIAR USUÁRIO - Falha (Login duplicado)
//Tenta criar um usuário com o mesmo login do usuário já criado.

POST {{host}}/api/usuarios/registrar
Content-Type: application/json

{
"nomeUsuario": "João Diferente",
"login": "joao.silva",
"senha": "Senha123*",
"setorUsuario": "Colaborador"
}

################################################################

#3. CRIAR USUÁRIO - Falha (Nome de usuário duplicado)
//Tenta criar um usuário com o mesmo nome de usuário do já existente.

POST {{host}}/api/usuarios/registrar
Content-Type: application/json

{
"nomeUsuario": "João Silva",
"login": "joao.diferente",
"senha": "Senha123*",
"setorUsuario": "Colaborador"
}

################################################################

#4. CRIAR USUÁRIO - Falha (Setor não informado)
//Tenta criar um usuário sem informar o setor.

POST {{host}}/api/usuarios/registrar
Content-Type: application/json

{
"nomeUsuario": "Maria Souza",
"login": "maria.souza",
"senha": "Senha123*"
}

################################################################

#5. LISTAR TODOS OS USUÁRIOS
//Lista todos os usuários cadastrados.

GET {{host}}/api/usuarios/listar